name: flame_network_assets
description: Network assets support for Flame.
version: 0.3.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_network_assets
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - assets
  - network-assets

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dev: ^1.0.0
  flame: ^1.17.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  dartdoc: ^6.3.0
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
