name: flame_network_assets
description: Network assets support for Flame.
version: 0.0.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_network_assets
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dev: ^1.0.0
  flame: ^1.6.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  mocktail: ^0.3.0
  path: ^1.8.2
  path_provider: ^2.0.12

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3
  flutter_test:
    sdk: flutter
