name: flame_network_assets_example
resolution: workspace
description: A flame network assets example.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flame: ^1.31.0
  flame_network_assets: ^0.3.3+15
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2
