name: flame_spine
description: Spine support for the Flame game engine. This uses the spine_flutter package and provides wrappers and components to be used inside Flame.
version: 0.1.1+9
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_sprine
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.14.0
  flutter:
    sdk: flutter
  spine_flutter: ^4.2.18

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
  test: any

assets:
  assets/logo_flame.png
