name: flame_spine
resolution: workspace
description: Spine support for the Flame game engine. This uses the spine_flutter package and provides wrappers and components to be used inside Flame.
version: 0.2.2+11
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_spine
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - animations

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  collection: ^1.17.1
  flame: ^1.28.1
  flutter:
    sdk: flutter
  spine_flutter: ^4.2.33

dev_dependencies:
  flame_lint: ^1.3.0
  flutter_test:
    sdk: flutter
  test: any

assets:
  assets/logo_flame.png
