name: flame_spine
description: Spine support for the Flame game engine. This uses the spine_flutter package and provides wrappers and components to be used inside Flame.
version: 0.1.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_sprine
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.0
  flame: ^1.7.3
  flutter:
    sdk: flutter
  spine_flutter: ^4.1.2

dev_dependencies:
  flame_lint: ^0.2.0+2
  flutter_test:
    sdk: flutter
  test: any

assets:
  assets/logo_flame.png
