name: flame_kenney_xml_example
resolution: workspace
description: "An example for the `XmlSpriteSheet` used to load kenney.nl assets."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.28.1
  flame_kenney_xml: ^0.1.1+11
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.3.0

flutter:
  assets:
    - assets/
    - assets/images/
