name: flame_noise
description: Integrate the fast_noise package into Flame
version: 0.3.2
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_noise
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - noise

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  fast_noise: ^2.0.0
  flame: ^1.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.2.1
  flame_test: ^1.17.0
  test: any