name: flame_noise
resolution: workspace
description: Integrate the fast_noise package into Flame
version: 0.3.2+9
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_noise
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - noise

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  fast_noise: ^2.0.0
  flame: ^1.27.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.3.0
  flame_test: ^1.18.3
  test: any