name: flame_flare_example
description: Flame sample for using Flare animations
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flame: ^1.3.0
  flame_flare: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.1.2
flutter:
  assets:
    - assets/Bob_Minion.flr
