name: flame_flare_example
description: Flame sample for using Flare animations
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flame:
    path: ../../flame
  flame_flare:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint:
    path: ../../flame_lint

flutter:
  assets:
    - assets/Bob_Minion.flr
