name: flame_texturepacker_example
description: An example of how to use the flame_texturepacker package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flame: ^1.17.0
  flame_texturepacker: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2

flutter:
  assets:
    - assets/