name: flame_texturepacker_example
description: An example of how to use the flame_texturepacker package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.21.0
  flame_texturepacker: ^4.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.2.1

flutter:
  assets:
    - assets/images/