name: flame_texturepacker_example
resolution: workspace
description: An example of how to use the flame_texturepacker package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.30.1
  flame_texturepacker: ^4.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.1

flutter:
  assets:
    - assets/images/