name: flame_texturepacker_example
resolution: workspace
description: An example of how to use the flame_texturepacker package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flame: ^1.35.1
  flame_texturepacker: ^5.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2

flutter:
  assets:
    - assets/images/