name: flame_bloc_example
description: Example game using the flame_bloc package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.9.0
  flame_bloc: ^1.10.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
