name: flame_bloc_example
description: Example game using the flame_bloc package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flame: ^1.5.0
  flame_bloc: ^1.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flame_lint: ^0.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
