name: flame_bloc_example
resolution: workspace
description: Example game using the flame_bloc package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  equatable: ^2.0.5
  flame: ^1.30.1
  flame_bloc: ^1.12.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
