name: flame_bloc_example
description: Example game using the flame_bloc package

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  equatable: ^2.0.5
  flame: ^1.22.0
  flame_bloc: ^1.12.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  flame_lint: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
