name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.17.0
homepage: https://github.com/flame-engine/flame
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  meta: ^1.9.1
  ordered_set: ^5.0.1
  vector_math: ^2.1.4

dev_dependencies:
  canvas_test: ^0.2.0
  dartdoc: ^6.3.0
  flame_lint: ^1.1.2
  flame_test: ^1.16.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  test: any

screenshots:
  - description: The Flame logo.
    path: screenshots/logo.png
