name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.3.0
homepage: https://github.com/flame-engine/flame

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  ordered_set: ^5.0.0
  vector_math: ^2.1.1

dev_dependencies:
  canvas_test: ^0.2.0
  dartdoc: ^4.1.0
  flame_lint: ^0.1.2
  flame_test: ^1.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: any
