name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.0.0-releasecandidate.13
homepage: https://github.com/flame-engine/flame

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  ordered_set: ^3.2.0
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  dart_code_metrics: ^4.1.0
  dartdoc: ^0.42.0
  mocktail: ^0.1.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

flutter:
  uses-material-design: false
