name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.1.1
homepage: https://github.com/flame-engine/flame

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  collection: ^1.15.0
  ordered_set: ^5.0.0
  vector_math: ^2.1.1

dev_dependencies:
  dartdoc: ^4.1.0
  mocktail: ^0.2.0
  canvas_test: ^0.2.0
  flame_test: ^1.4.0
  flame_lint: ^0.0.1
  test: any
  flutter_test:
    sdk: flutter
