name: flame
resolution: workspace
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.28.1
homepage: https://github.com/flame-engine/flame
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - game-engine
  - games
  - animations

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  meta: ^1.12.0
  ordered_set: ^7.0.0
  vector_math: ^2.1.4

dev_dependencies:
  benchmark_harness: ^2.3.1
  canvas_test: ^0.2.0
  dartdoc: ^8.0.8
  flame_lint: ^1.3.0
  flame_test: ^1.19.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: any

screenshots:
  - description: The Flame logo.
    path: screenshots/logo.png
