name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 1.0.0-releasecandidate.16
homepage: https://github.com/flame-engine/flame

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  ordered_set: ^4.0.0
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  dartdoc: ^0.42.0
  mocktail: ^0.1.4
  canvas_test: ^0.1.1
  flame_test:
    path: ../flame_test
  flame_lint:
    path: ../flame_lint
