name: flame
description: A minimalist Flutter game engine, provides a nice set of somewhat independent modules you can choose from.
version: 2.0.0
homepage: https://github.com/flame-engine/flame
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - game-engine
  - games
  - animations

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  meta: ^1.12.0
  ordered_set: ^6.0.0
  vector_math: ^2.1.4

dev_dependencies:
  canvas_test: ^0.2.0
  dartdoc: ^8.0.8
  flame_lint: ^2.0.0
  flame_test: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: any

screenshots:
  - description: The Flame logo.
    path: screenshots/logo.png
