name: flame_splash_screen
resolution: workspace
description: Style your flame game with a beautiful splash screen with logo reveal. Simple to use but still customizable.
version: 0.3.1+2
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_splash_screen
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  assets:
   - assets/
