name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.8.2-releasecandidate.15
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flame:
    path: ../flame
  forge2d: ^0.8.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  dartdoc: ^0.42.0
  flame_lint:
    path: ../flame_lint

