name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.11.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flame: ^1.1.1
  forge2d: ">=0.11.0 <0.12.0"
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.0.1
  mocktail: ^0.3.0
  test: any
