name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.18.2+3
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - forge2d
  - physics

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flame: ^1.22.0
  flutter:
    sdk: flutter
  forge2d: ^0.13.1

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.2.1
  flame_test: ^1.17.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: any
