name: flame_forge2d
resolution: workspace
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.19.0+6
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - forge2d
  - physics

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flame: ^1.32.0
  flutter:
    sdk: flutter
  forge2d: ^0.14.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.4.2
  flame_test: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: any
