name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.16.0+3
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_forge2d
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flame: ^1.13.0
  flutter:
    sdk: flutter
  forge2d: ">=0.12.2 <0.13.0"

dev_dependencies:
  dartdoc: ^6.3.0
  flame_lint: ^1.1.2
  flame_test: ^1.15.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  test: any
