name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.8.0-releasecandidate.13
homepage: https://github.com/flame-engine/flame_forge2d
publish_to: 'none'


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  flame:
    path: ../flame
  forge2d: ^0.8.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  dartdoc: ^0.42.0
  dart_code_metrics: ^3.2.2
