name: jenny
resolution: workspace
description: YarnSpinner narrative game tools equivalent for Dart.
version: 1.4.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_jenny/jenny
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - yarnspinner
  - text

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.12.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.4.0
  test: any
