name: jenny
description: Yarn Spinner equivalent for Dart.
version: 0.0.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_jenny/jenny
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3
  test: any
