name: jenny
description: YarnSpinner equivalent for Dart.
version: 1.0.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_jenny/jenny
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.2.0
  test: any
