name: jenny
description: YarnSpinner narrative game tools equivalent for Dart.
version: 1.3.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_jenny/jenny
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - yarnspinner
  - text

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  dartdoc: ^6.3.0
  flame_lint: ^1.1.2
  test: any
