name: flame_studio
resolution: workspace
description: An IDE-like environment for developing and debugging Flame games.
version: 0.0.0
publish_to: none
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_studio
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.32.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  meta: ^1.12.0

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter
  test: any

assets:
  assets/logo_flame.png
