name: flame_kenney_xml
resolution: workspace
description: "Support for Kenney XML spritesheets for the Flame game engine. This package parses XML files produced by Kenney."
version: 0.1.1+16
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_kenney_xml
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - spritesheet
  - kenney
  - tilemap

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flame: ^1.32.0
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.11
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
