name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  behavior_tree: ^0.1.3+2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
