name: flame_isolate
resolution: workspace
description: Flame wrapper for integral_isolates making multi-threading easy in Flame
version: 0.6.2+19
repository: https://github.com/flame-engine/flame/blob/main/packages/flame_isolate
topics:
  - flame
  - isolate

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flame: ^1.35.0
  flutter:
    sdk: flutter
  integral_isolates: ^0.5.1

dev_dependencies:
  flame_lint: ^1.4.2
  flame_test: ^2.2.1
  flutter_test:
    sdk: flutter
  test: any

