name: flame_isolate
resolution: workspace
description: Flame wrapper for integral_isolates making multi-threading easy in Flame
version: 0.6.2+4
repository: https://github.com/flame-engine/flame/blob/main/packages/flame_isolate
topics:
  - flame
  - isolate

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flame: ^1.23.0
  flutter:
    sdk: flutter
  integral_isolates: ^0.5.1

dev_dependencies:
  flame_lint: ^1.2.1
  flame_test: ^1.17.4
  flutter_test:
    sdk: flutter
  test: any

