name: flame_isolate
description: Flame wrapper for integral_isolates making multi-threading easy in Flame
version: 0.6.0
repository: https://github.com/flame-engine/flame/blob/main/packages/flame_isolate

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.19.0

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter
  integral_isolates: ^0.5.1

dev_dependencies:
  flame_lint: ^1.1.2
  flame_test: ^1.16.0
  flutter_test:
    sdk: flutter
  test: any

