name: flame_isolate
description: Flame wrapper for integral_isolates making multi-threading easy in Flame
version: 0.4.0
homepage: https://github.com/lohnn/integral_isolates

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.8.0
  flutter:
    sdk: flutter
  integral_isolates: ^0.3.0

dev_dependencies:
  flame_lint: ^0.2.0+3
  flame_test: ^1.11.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  test: any

