name: flame_isolate
resolution: workspace
description: Flame wrapper for integral_isolates making multi-threading easy in Flame
version: 0.6.2+11
repository: https://github.com/flame-engine/flame/blob/main/packages/flame_isolate
topics:
  - flame
  - isolate

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.28.1
  flutter:
    sdk: flutter
  integral_isolates: ^0.5.1

dev_dependencies:
  flame_lint: ^1.3.0
  flame_test: ^1.19.1
  flutter_test:
    sdk: flutter
  test: any

