name: rogue_shooter
description: A simple game benchmarking the collision detection performance.
homepage: https://github.com/flame-engine/flame/tree/main/examples/games/rogue_shooter
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2

flutter:
  assets:
    - assets/images/rogue_shooter/
