name: forge2d_samples
description: Flame Forge2D (box2d) samples

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  flutter:
    sdk: flutter
  flame_forge2d:
    path: ../
  dashbook: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint:
    path: ../../flame_lint


flutter:
  uses-material-design: true
  assets:
    - assets/images/pizza.png
    - assets/images/chopper.png
