name: flame_forge2d_example
description: Flame Forge2D (box2d) samples

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  dashbook: ^0.1.12
  flame: ^1.10.1
  flame_forge2d: ^0.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
