name: flame_forge2d_example
resolution: workspace
description: Flame Forge2D (box2d) samples

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flame: ^1.35.1
  flame_forge2d: ^0.19.2+4
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
