blank_issues_enabled: false
contact_links:
  - name: I have some questions about Flame.
    url: https://stackoverflow.com/tags/flame
    about: Ask your questions on StackOverflow! The community is always willing to help out.
  - name: Join us on Discord!
    url: https://discord.gg/pxrBmy4
    about: Ask your questions in our community!
