name: flame_devtools
resolution: workspace
description: "The DevTools extension for Flame"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animated_tree_view: ^2.3.0
  devtools_app_shared: ^0.3.1
  devtools_extensions: ^0.3.1
  flame: ^1.32.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flame_lint: ^1.4.2

flutter:
  uses-material-design: true
