name: flame_lottie
resolution: workspace
description: Flame wrapper for Lottie by AirBnB. This package implements a bridge between Lottie and Flame, allowing to load and display Lottie animations.
version: 0.4.2+20
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lottie
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - lottie
  - animations

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flame: ^1.35.1
  flutter:
    sdk: flutter
  lottie: ^3.1.2

dev_dependencies:
  flame_lint: ^1.4.2
  flame_test: ^2.2.2
  flutter_test:
    sdk: flutter
