name: flame_lottie
description: Flame wrapper for Lottie by AirBnB. This package implements a bridge between Lottie and Flame, allowing to load and display Lottie animations.
version: 0.4.0+1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lottie
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - lottie
  - animations

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter
  lottie: ^2.3.2

dev_dependencies:
  flame_lint: ^1.1.2
  flame_test: ^1.16.1
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
