name: flame_lottie
description: Flame wrapper for Lottie by AirBnB. This package implements a bridge between Lottie and Flame, allowing to load and display Lottie animations.
version: 0.2.0+3
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lottie
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flame: ^1.7.4
  flutter:
    sdk: flutter
  lottie: ^2.3.2

dev_dependencies:
  flame_lint: ^0.2.0+3
  flame_test: ^1.11.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
