name: flame_lottie
description: Flame wrapper for Lottie by AirBnB. This package implements a bridge between Lottie and Flame, allowing to load and display Lottie animations.
version: 0.0.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lottie
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flame: ^1.4.0
  flutter:
    sdk: flutter
  lottie: ^1.4.3

dev_dependencies:
  flame_lint: ^0.1.3
  flame_test: ^1.8.0
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
