name: flame_riverpod
resolution: workspace
description: Helpers for using Riverpod - a reactive caching and data-binding framework, in conjunction with Flame.
version: 5.4.17
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_riverpod
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - state-management

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.30.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1

dev_dependencies:
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter
