name: flame_riverpod
description: Helpers for using Riverpod - a reactive caching and data-binding framework, in conjunction with Flame.
version: 5.4.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_riverpod
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - state-management

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
