name: flame_markdown_example
resolution: workspace
description: Simple project to showcase the usage of flame_markdown
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.25.0
  flame_markdown: ^0.2.3+2
  flutter:
    sdk: flutter
  markdown: ^7.1.1

dev_dependencies:
  flame_lint: ^1.2.2

flutter:
  assets:
    - assets/
