name: flame_markdown_example
resolution: workspace
description: Simple project to showcase the usage of flame_markdown
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.30.1
  flame_markdown: ^0.2.4+7
  flutter:
    sdk: flutter
  markdown: ^7.3.0

dev_dependencies:
  flame_lint: ^1.4.1

flutter:
  uses-material-design: false
  assets:
    - assets/