name: flame_markdown_example
resolution: workspace
description: Simple project to showcase the usage of flame_markdown
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flame: ^1.31.0
  flame_markdown: ^0.2.4+8
  flutter:
    sdk: flutter
  markdown: ^7.3.0

dev_dependencies:
  flame_lint: ^1.4.2

flutter:
  uses-material-design: false
  assets:
    - assets/