name: flame_behaviors_example
resolution: workspace
description: A Very Good Example for the Flame Behavior Pattern.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flame: ^1.34.0
  flame_behaviors: ^1.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2

