name: flame_sprite_fusion
resolution: workspace
description: "Sprite Fusion support for the Flame game engine. This package parses and renders tilemaps exported from Sprite Fusion tool."
version: 0.2.2+3
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_sprite_fusion
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - tilemap

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  collection: ^1.19.1
  flame: ^1.35.1
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2
  flame_test: ^2.2.2
  flutter_test:
    sdk: flutter
