name: flame_sprite_fusion
description: "Sprite Fusion support for the Flame game engine. This package parses and renders tilemaps exported from Sprite Fusion tool."
version: 0.1.3+1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_sprite_fusion
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - tilemap

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.2.1
  flame_test: ^1.17.1
  flutter_test:
    sdk: flutter
