name: flame_tiled
description: Tiled support for the Flame game engine. This uses the tiled package and provides wrappers and components to be used inside Flame.
version: 1.4.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_tiled

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flame: ^1.1.1
  tiled: ^0.8.1
  xml: ^5.3.0
  meta: ^1.7.0
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.0.1
  test: any
