name: flame_tiled
resolution: workspace
description: Tiled support for the Flame game engine. This uses the tiled package and provides wrappers and components to be used inside Flame.
version: 3.0.5
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_tiled
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - tiled
  - tilemap

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  collection: ^1.17.1
  flame: ^1.30.1
  flutter:
    sdk: flutter
  meta: ^1.12.0
  tiled: ^0.11.0
  xml: ^6.3.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.4.1
  flutter_test:
    sdk: flutter
  test: any
