name: flame_tiled
description: Tiled support for the Flame game engine. This uses the tiled package and provides wrappers and components to be used inside Flame.
version: 1.6.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_tiled

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.15.0
  flame: ^1.2.1
  flutter:
    sdk: flutter
  meta: ^1.7.0
  tiled: ^0.8.4
  xml: ^5.3.0

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.1.1
  test: any
