name: flame_tiled
description: Tiled support for the Flame game engine. This uses the tiled package and provides wrappers and components to be used inside Flame.
version: 1.15.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_tiled
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.10.0
  flutter:
    sdk: flutter
  meta: ^1.9.1
  tiled: ">=0.10.0 <0.11.0"
  xml: ^6.3.0

dev_dependencies:
  dartdoc: ^6.2.2
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter
  test: any
