name: flame_test
description: A package with classes to help testing applications using Flame
version: 0.1.0-releasecandidate.13
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_test
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flame:
    path: ../flame
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
  test: ^1.17.10
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  dartdoc: ^0.42.0
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.1.0
