name: flame_test
resolution: workspace
description: A package with classes to help testing applications using Flame
version: 2.0.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_test
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - test
  - testing

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.30.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.12.0
  test: ^1.24.1
  typed_data: ^1.4.0
  vector_math: ^2.1.4

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.4.1