name: flame_test
description: A package with classes to help testing applications using Flame
version: 1.5.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_test

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flame: ^1.2.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.7.0
  test: ^1.17.12
  vector_math: ^2.1.1

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.0.1
