name: flame_rive_example
resolution: workspace
description: A testbed for flame_rive
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.25.0
  flame_rive: ^1.10.9
  flutter:
    sdk: flutter
  rive: ^0.12.3

dev_dependencies:
  flame_lint: ^1.2.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
