name: flame_rive_example
description: A testbed for flame_rive
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  rive: 0.8.4
  flame_rive:
    path: ../
  flame:
    path: ../../flame
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint:
    path: ../../flame_lint

flutter:
  uses-material-design: true
  assets:
    - assets/
