name: flame_rive_example
description: A testbed for flame_rive
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.3.0
  flame_rive: ^1.5.1
  flutter:
    sdk: flutter
  rive: 0.9.0

dev_dependencies:
  flame_lint: ^0.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
