name: flame_console
resolution: workspace
description: "An extensible and customizable console to help debug Flame games."
version: 0.1.2
homepage:

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  args: ^2.5.0
  flame: ^1.23.0
  flutter:
    sdk: flutter
  terminui: ^0.1.0

dev_dependencies:
  flame_lint: ^1.2.1
  flame_test: ^1.17.4
  flutter_test:
    sdk: flutter
