name: flame_console
resolution: workspace
description: "An extensible and customizable console to help debug Flame games."
version: 0.1.2+8
repository: https://github.com/flame-engine/flame/tree/main/packages/flame_console
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - games
  - utils

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  args: ^2.5.0
  flame: ^1.29.0
  flutter:
    sdk: flutter
  terminui: ^0.2.0

dev_dependencies:
  flame_lint: ^1.4.0
  flame_test: ^1.19.2
  flutter_test:
    sdk: flutter
