name: trex_game
description: A clone of the classic browser T-Rex game.
homepage: https://github.com/flame-engine/flame/tree/main/examples/games/trex/
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.16.0
  flame: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
