name: flame_isolate_example
description: Flame game example for running threaded workloads

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.10.0
  flame_isolate: ^0.5.0+2
  flutter:
    sdk: flutter
  integral_isolates: ^0.3.0
  quiver: ^3.2.1

dev_dependencies:
  flame_lint: ^1.1.1
flutter:
  assets:
    - assets/images/
