name: flame_isolate_example
resolution: workspace
description: Flame game example for running threaded workloads

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  collection: ^1.18.0
  flame: ^1.28.1
  flame_isolate: ^0.6.2+11
  flutter:
    sdk: flutter
  quiver: ^3.2.1

dev_dependencies:
  flame_lint: ^1.3.0
flutter:
  assets:
    - assets/images/
