name: flame_isolate_example
description: Flame game example for running threaded workloads

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.18.0
  flame: ^1.21.0
  flame_isolate: ^0.6.2+2
  flutter:
    sdk: flutter
  quiver: ^3.2.1

dev_dependencies:
  flame_lint: ^1.2.1
flutter:
  assets:
    - assets/images/
