name: flame_tiled_example
description: Simple project to showcase the usage of flame_tiled
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.10.0
  flame_tiled: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/tiles/map.tmx
    - assets/images/level_ice_tileset.png
    - assets/images/level_standard_tileset.png
    - assets/images/repeatable_background.png
    - assets/images/coins.png
