name: flame_tiled_example
resolution: workspace
description: Simple project to showcase the usage of flame_tiled
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.30.1
  flame_tiled: ^3.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.1
flutter:
  uses-material-design: true
  assets:
    - assets/tiles/map.tmx
    - assets/images/level_ice_tileset.png
    - assets/images/level_standard_tileset.png
    - assets/images/repeatable_background.png
    - assets/images/coins.png
