name: flame_tiled_example
description: Simple project to showcase the usage of flame_tiled
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.3.0
  flame_tiled: ^1.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/tiles/map.tmx
    - assets/images/level_ice_tileset.png
    - assets/images/level_standard_tileset.png
    - assets/images/repeatable_background.png
    - assets/images/coins.png
