name: flame_jenny
resolution: workspace
description: Flame bridge package to Jenny (a Dart port of Yarn Spinner).
version: 1.0.0
publish_to: none
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_jenny
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  collection: ^1.17.1
  flame: ^1.29.0
  flutter:
    sdk: flutter
  jenny: ^1.4.0
  meta: ^1.12.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.4.0
  test: any
