name: flame_jenny
description: Flame bridge package to Jenny (a Dart port of Yarn Spinner).
version: 1.0.0
publish_to: none
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_jenny
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.19.0

dependencies:
  collection: ^1.17.1
  flame: ^1.15.0
  flutter:
    sdk: flutter
  jenny: ^1.2.1
  meta: ^1.9.1

dev_dependencies:
  dartdoc: ^6.3.0
  flame_lint: ^1.1.2
  test: any
