name: flame_oxygen
resolution: workspace
description: Integrate the Oxygen ECS with the Flame Engine.
version: 0.2.3+20
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_oxygen
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flame: ^1.35.1
  flutter:
    sdk: flutter
  oxygen: ^0.3.1

dev_dependencies:
  dartdoc: ^9.0.0
  flame_lint: ^1.4.2