name: flame_oxygen
description: Integrate the Oxygen ECS with the Flame Engine.
version: 0.1.5
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_oxygen

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flame: ^1.3.0
  flutter:
    sdk: flutter
  oxygen: ^0.2.0

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.1.2