name: doc_flame_examples
description: Documentation examples
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.4.0
  flame_rive: ^1.5.2
  flutter:
    sdk: flutter
  rive: ^0.9.1


dev_dependencies:
  flame_lint: ^0.1.3

flutter:
  assets:
    - assets/
    - assets/images/