name: doc_flame_examples
resolution: workspace
description: Documentation examples
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flame: ^1.35.1
  flame_rive: ^1.10.23
  flutter:
    sdk: flutter
  flutter_shaders:
  web: ^1.1.0

dev_dependencies:
  flame_lint: ^1.4.2

flutter:
  shaders:
    - packages/flutter_shaders/shaders/pixelation.frag
  assets:
    - assets/
    - assets/images/
