name: doc_flame_examples
resolution: workspace
description: Documentation examples
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.26.0
  flame_rive: ^1.10.10
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flame_lint: ^1.2.3

flutter:
  assets:
    - assets/
    - assets/images/
