name: doc_flame_examples
description: Documentation examples
version: 1.0.0
publish_to: none

environment:
  sdk: ^2.16.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame:
    path: ../../../packages/flame
