name: flame_audio
description: |
  Audio support for the Flame game engine, basically a thin wrapper around the audioplayers package.
version: 2.10.5
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - audio

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  audioplayers: ^6.0.0
  flame: ^1.21.0
  flutter:
    sdk: flutter
  synchronized: ^3.1.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
