name: flame_audio
description: Audio support for the Flame game engine. This containst all audio related code will live in the future, using the audioplayers package.
version: 1.3.3
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  audioplayers: ^1.0.1
  flame: ^1.5.0
  flutter:
    sdk: flutter
  synchronized: ^3.0.0

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3