name: flame_audio
description: |
  Audio support for the Flame game engine, basically a thin wrapper around the audioplayers package.
version: 2.0.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  audioplayers: ^4.0.0
  flame: ^1.7.0
  flutter:
    sdk: flutter
  synchronized: ^3.0.1

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.2.0+1