name: flame_audio
resolution: workspace
description: |
  Audio support for the Flame game engine, basically a thin wrapper around the audioplayers package.
version: 2.11.14
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - audio

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  audioplayers: ^6.2.0
  flame: ^1.35.1
  flutter:
    sdk: flutter
  synchronized: ^3.1.0

dev_dependencies:
  dartdoc: ^9.0.0
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
