name: flame_audio
description: Audio support for the Flame game engine. This containst all audio related code will live in the future, using the audioplayers package.
version: 1.0.0-rc.1
homepage: https://github.com/flame-engine/flame_audio
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flame:
    path: ../flame
  audioplayers: ^0.19.0
  synchronized: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^3.2.2
  dartdoc: ^0.42.0
  flutter_test:
    sdk: flutter
  test: ^1.9.4
