name: flame_audio
resolution: workspace
description: |
  Audio support for the Flame game engine, basically a thin wrapper around the audioplayers package.
version: 2.11.5
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_audio
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - audio

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  audioplayers: ^6.2.0
  flame: ^1.28.1
  flutter:
    sdk: flutter
  synchronized: ^3.1.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
