name: flame_sprite_fusion_example
resolution: workspace
description: "An example for the SpriteFusionTilemapComponent."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flame: ^1.32.0
  flame_sprite_fusion: ^0.2.0+3
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
