name: flame_behavior_tree
resolution: workspace
description: A bridge package that integrates behavior_tree package with flame.
version: 0.1.3+13
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_behavior_tree
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  behavior_tree: ^0.1.3+2
  flame: ^1.30.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.0
  flame_test: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
