name: flame_behavior_tree
description: A bridge package that integrates behavior_tree package with flame.
version: 0.1.3
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_behavior_tree
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  behavior_tree: ^0.1.3
  flame: ^1.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.2.1
  flame_test: ^1.17.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
