name: widgets
description: A Flutter project showcasing Flame's widgets.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.24.0-10.2.pre"

dependencies:
  flutter:
    sdk: flutter
  flame:
      path: ../../../
  dashbook: ^0.1.0-nullsafety

  cupertino_icons: ^1.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/nine_tile_box.png
    - assets/images/buttons.png
    - assets/images/shield.png
    - assets/images/bomb_ptero.png
