name: flame_splash_screen_example
resolution: workspace
description: Flame Splash Screen Example
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flame_splash_screen: ^0.3.1+2
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_test:
    sdk: flutter

