name: flame_3d
description: Experimental 3D support for the Flame Engine
version: 0.1.0-dev.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_3d
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter
  flutter_gpu:
  meta: ^1.9.1
  vector_math: ^2.1.4

dev_dependencies:
  flame_lint: ^1.1.2
  flame_test: ^1.15.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/shaders/
