name: flame_3d
resolution: workspace
description: Experimental 3D support for the Flame Engine
version: 0.1.0-dev.13
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_3d
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flame: ^1.30.0
  flutter:
    sdk: flutter
  flutter_gpu:
    sdk: flutter
  meta: ^1.12.0
  ordered_set: ^8.0.0
  vector_math: ^2.1.4

dev_dependencies:
  flame_lint: ^1.4.0
  flame_test: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/shaders/
