name: flame_lint
description: Flame lint package
version: 2.0.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lint
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - lints

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  lints: ^4.0.0

dev_dependencies:
  dartdoc: ^8.0.8
