name: flame_lint
resolution: workspace
description: Flame lint package
version: 1.4.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lint
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - lints

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  lints: ^5.1.1

dev_dependencies:
  dartdoc: ^8.0.8
