name: flame_lint
description: Flame lint package
version: 0.0.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_lint
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  dartdoc: ^5.0.1
