name: flame_oxygen_example
description: Flame Oxygen example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.11.0
  flame_oxygen: ^0.1.9+4
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/pizza.png
    - assets/images/chopper.png
