name: flame_oxygen_example
resolution: workspace
description: Flame Oxygen example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.28.1
  flame_oxygen: ^0.2.3+11
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.3.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/pizza.png
    - assets/images/chopper.png
