name: spritesheet
description: Flame sample game showcasing spritesheet features

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dashbook: 0.0.6
  flame:
      path: ../../../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/spritesheet.png
