name: klondike
resolution: workspace
description: Klondike tutorial
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flame: ^1.30.1
  flutter:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flame_lint: ^1.4.1

flutter:
  assets:
    - assets/images/
