name: flame_bloc
description: Bloc integration to Flame games
version: 1.2.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_bloc

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  flame: ^1.1.0
  flutter_bloc: ^8.0.1

dev_dependencies:
  dartdoc: ^4.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flame_test: ^1.2.0
  mocktail: ^0.2.0
  flame_lint: ^0.0.1
