name: flame_bloc
description: Bloc integration to Flame games
version: 1.7.0
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_bloc

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.2
  flame: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  meta: ^1.7.0

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.1.2
  flame_test: ^1.7.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
