name: flame_bloc
description: Integration for the Bloc state management library to Flame games.
version: 1.8.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_bloc
funding:
  - https://patreon.com/bluefireoss
  - https://www.buymeacoffee.com/bluefire

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  bloc: ^8.0.2
  flame: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  meta: ^1.7.0

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3
  flame_test: ^1.9.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
