name: flame_bloc
description: Bloc integration to Flame games
version: 1.0.0-releasecandidate.15
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_bloc
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.0
  flame:
    path: ../flame
  flutter_bloc: ^7.3.0

dev_dependencies:
  dartdoc: ^0.42.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flame_test:
    path: ../flame_test
  mocktail: ^0.1.4
  flame_lint:
    path: ../flame_lint
