name: flame_bloc
resolution: workspace
description: Integration for the Bloc state management library to Flame games.
version: 1.12.12
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_bloc
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss
topics:
  - flame
  - state-management

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  bloc: ">=8.1.1 <10.0.0"
  flame: ^1.28.1
  flutter:
    sdk: flutter
  flutter_bloc: ">=8.1.2 <10.0.0"
  meta: ^1.12.0

dev_dependencies:
  dartdoc: ^8.0.8
  flame_lint: ^1.3.0
  flame_test: ^1.19.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
