name: flame_riverpod_example
resolution: workspace
description: Showcasing the flame_riverpod functionality.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flame: ^1.25.0
  flame_riverpod: ^5.4.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flame_lint: ^1.2.2
  flutter_test:
    sdk: flutter
