name: flame_riverpod_example
description: Showcasing the flame_riverpod functionality.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flame: ^1.16.0
  flame_riverpod: ^5.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
