name: flame_riverpod_example
description: Showcasing the flame_riverpod functionality.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  flame: ^1.6.0
  flame_riverpod: ^4.0.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
