name: padracing
description: A sample game featuring Flame and Forge2D for DartPad
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  flame: ^1.5.0
  flame_forge2d: ^0.12.2
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  url_launcher: ^6.1.2

dev_dependencies:
  flame_lint: ^0.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
