name: padracing
resolution: workspace
description: A sample game featuring Flame and Forge2D for DartPad
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  flame: ^1.30.0
  flame_forge2d: ^0.19.0+3
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.1.11

dev_dependencies:
  flame_lint: ^1.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
