name: flame_svg
description: Package to add SVG rendering support for the Flame game engine
version: 1.10.1
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_svg
funding:
  - https://opencollective.com/blue-fire
  - https://github.com/sponsors/bluefireteam
  - https://patreon.com/bluefireoss

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flame: ^1.17.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5

dev_dependencies:
  dartdoc: ^6.3.0
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  test: any
