name: flame_svg
description: Package to add SVG rendering support for the Flame game engine
version: 1.0.0-releasecandidate.15
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_svg
publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flame:
    path: ../flame
  flutter_svg: ^0.22.0
  flutter:
    sdk: flutter

dev_dependencies:
  dartdoc: ^0.42.0
  flame_lint:
    path: ../flame_lint
