name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@main
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: examples
          webRenderer: canvaskit

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger building the docs
        run: |
          curl -XPOST -u "${{ secrets.DOCS_BUILD_DISPATCH }}" \
          -H "Accept:application/vnd.github" \
          -H "Content-Type:application/json" \
          https://api.github.com/repos/flame-engine/flame-docs-site/actions/workflows/13757924/dispatches \
          --data '{"ref": "main" }'
