name: example
description: Simple project to showcase the usage of flame_audio

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flame:
    path: ../../flame
  flame_audio:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint:
    path: ../../flame_lint

flutter:
  assets:
    - assets/audio/music/bg_music.ogg
    - assets/audio/sfx/fire_1.mp3
    - assets/audio/sfx/fire_2.mp3
