name: flame_audio_example
description: Simple project to showcase the usage of flame_audio

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.9.0
  flame_audio: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.1

flutter:
  assets:
    - assets/audio/music/bg_music.ogg
    - assets/audio/sfx/fire_1.mp3
    - assets/audio/sfx/fire_2.mp3
